server:
  port: 8082

spring:

  datasource:
    url: jdbc:h2:mem:inventory_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true # 엔티티로 테이블을 생성한 후에 data.sql 실행
    hibernate:
      ddl-auto: update
    show-sql: true
    
  cloud:
    # 이벤트 메시지 처리 함수 (메서드 = 빈 이름)
    function:
      definition: processInventory
    stream:
      bindings:
        # 입력 바인딩 (함수이름-in-인덱스)
        processInventory-in-0:
          destination: order.created-topic # Producer가 메시지를 발행한 토픽
          group: inventory-group # Consumer는 반드시 그룹이 필요 (LB 및 데이터 유실 방지)

        inventory-reserved-out-0:
          destination: inventory-success-topic

        inventory-failed-out-0:
          destination: inventory-failure-topic